# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: BSD-3-Clause
---
name: 'Dependabot auto approvals'

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  package:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@79c78eb22c112f57f7791b40ddf8d49f6bcdd3c4 # v1.2.85
    secrets: inherit
