# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: BSD-3-Clause
---
name: 'Dependabot auto approvals'

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  package:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@88f0031a49c2fa0715e3dc72c137d43903bbefa7 # v1.2.92
    secrets: inherit
