# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: BSD-3-Clause
---
name: 'Dependabot auto approvals'

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  package:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@c6bbf7493e3325be3d17c4d4a2481e06291b9bb0 # v1.2.79
    secrets: inherit
