# SPDX-FileCopyrightText: 2022-2023 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: BSD-3-Clause
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
    tags:
      - 'v*'

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/ci.yml@d9a09443af8081b29e4021ed0e7f55e02702c88a # v1.2.77
    secrets: inherit
