# SPDX-FileCopyrightText: 2022-2023 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: BSD-3-Clause
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
    tags:
      - 'v*'

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/ci.yml@144663466e8a39089b78d9bbc98b826534810d1c # v1.2.71
    secrets: inherit
