# SPDX-FileCopyrightText: 2022-2023 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: BSD-3-Clause
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
    tags:
      - 'v*'

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/ci.yml@c52923b68e72e328c8dc85e4f3815be13aa95f54 # v1.2.83
    secrets: inherit
